# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "public_network"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu_docker"
    vb.memory = 6144
    vb.cpus = 4
  end
  pkg_cmd = "curl -sSL https://get.docker.com/ | sh; "
  pkg_cmd << "usermod -a -G docker vagrant; "
  config.vm.provision :shell, :inline => pkg_cmd
end